version: '3.8'

services:
  client:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=/api/v1
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge